### PR TITLE
add license-check-allowed-additional

### PR DESCRIPTION
**Pull request by Uzlopak**
I added a license-check-allowed-additional option. I will test it in my personal org.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@Fdawgs 
@mcollina 

Ok, seems to work 

https://github.com/Uzlopak/fastify-nextjs/runs/7649016690?check_suite_focus=true

But now 'CC0-1.0' pops up as license...

CC0-1.0 means public domain. Should I add this to our default allowed set?

**Review by mcollina — DISMISSED** [review]
lgtm

**Comment by Fdawgs** [comment]
Readme inputs need updating as well 😄 
https://github.com/fastify/workflows#inputs

**Comment by Uzlopak** [comment]
The readme adaptation is no issue. Just want to get a green light for the name ;)

**Comment by Uzlopak** [comment]
@Fdawgs 

added documentation

**Review by Fdawgs — APPROVED** [review]
Will rejig the input table formatting before cutting a release but lgtm

**Pull request merged**
