### PR TITLE
add kafka workflow

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Why are we adding this here even if it's just for a single plugin?

**Review by gurgunday — APPROVED** [review]

**Comment by gurgunday** [comment]
I feel like this is a good place to centralize service-related workflows

For instance, if I ever need to look for a specific workflow (like kafka), I might forget which plugin uses it and just check here

**Review by Fdawgs — DISMISSED** [review]

**Review by Fdawgs — APPROVED** [review]

**Review by gurgunday — APPROVED** [review]
lgtm

**Pull request merged**
