### PR TITLE
add Apache-2.0 to allowed licenses

### PR DESCRIPTION
**Pull request by Uzlopak**
See https://github.com/fastify/fastify-oauth2/pull/169#issuecomment-1202289206

Only consideration: Dont we need then to ship the code with the text of the Apache-2.0 license?

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Fdawgs** [comment]
I believe `Apache-2.0` is a permissive license like `MIT`, however I am not a lawyer

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
I looked over it. I think it is like MIT. As long the license file is in the npm package we should be good.

**Comment by Uzlopak** [comment]
@mcollina 

Should we merge and continue the failing projects?

**Review by Fdawgs — APPROVED** [review]

**Pull request merged**
