### PR TITLE
add license-check

### PR DESCRIPTION
**Pull request by Uzlopak**
Adds a job to check licenses like it is done in fastify core project

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Fdawgs** [comment]
Morning, so this can be revamped completely, as `actions/dependency-review-action` >=v2 supports license checking: https://github.com/actions/dependency-review-action#licenses

This action is used in the `dependency-review` job of these workflows.

It's a good excuse to move away from the `license-checker`  npm dependency as well, which looks to be no longer maintained.

**Comment by Uzlopak** [comment]
@Fdawgs 

I think I modified it accordingly.

**Review by Fdawgs — APPROVED** [review]

**Comment by Fdawgs** [comment]
Apologies, forgot to thank you when merging this @Uzlopak.

Thanks!

**Pull request merged**
