### PR TITLE
Updates for fastify v5

### LINKED ISSUE #106: Create a v4 set
A new `v4` tag should be create that points to a set of workflows that drop Node.js <=16. Any changes to `v3` should happen on the https://github.com/fastify/workflows/tree/v3.y.z branch.

### PR DESCRIPTION
**Pull request by nrayburn-tech**
Drop node <= 16 from workflows
Add node 21 to benchmark-pr
Add node 21 to ci-package-manager for yarn

Fixes #106, #92.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Comment by jsumners** [comment]
The v4 tag has been created.

**Comment by mcollina** [comment]
Let's hope this does not get auto-updated across the entire fleet, otherwise it would be a nightmare to revert.

**Comment by jsumners** [comment]
It shouldn't. But what in the actual eff Dependabot? https://github.com/fastify/releasify/pull/283

@Fdawgs I believe you have setup the majority of the Dependabot stuff. Do you know why it would automatically update the major versions of workflows?

**Comment by Fdawgs** [comment]
https://github.com/fastify/github-action-merge-dependabot working as intended.

**Comment by mcollina** [comment]
@Fdawgs would this land automatically then?

**Comment by Fdawgs** [comment]
> @Fdawgs would this land automatically then?

Unfortunately, yes. Can see it making its way through all the reps now. 😸

**Comment by jsumners** [comment]
We _really_ should not be updating _at least_ our own workflows's major version automatically. The whole point of the versioning, particularly in this repo, is to indicate breaking changes in the workflow.

**Comment by jsumners** [comment]
How do we stop the linked tool from updating all of our repos automatically for this?

**Comment by jsumners** [comment]
@nrayburn-tech I have removed the v4 tag for right now. To continue your work, use the git SHA. I will restore the v4 tag once we have fixed the above discussed problem.

**Pull request merged**
