### PR TITLE
Drop dependency review as it's imprecise

### PR DESCRIPTION
**Pull request by mcollina**
Ref: https://github.com/fastify/fastify-passport/pull/597
Ref: https://github.com/fastify/fastify-passport/pull/607

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
landing with admin permission to unblock CI

**Comment by mcollina** [comment]
I _think_ I've stripped out only that, is there more to the dependency-review action?
Feel free to re-add in a way that's not breaking the CI - this will never pass for Fastify or any other plugins in our ecosystem.

**Comment by Fdawgs** [comment]
> I _think_ I've stripped out only that, is there more to the dependency-review action? Feel free to re-add in a way that's not breaking the CI - this will never pass for Fastify or any other plugins in our ecosystem.

Cool beans, will re-add and at the same time remove the license checking component from the other two workflows in this repo as well. 😄

**Comment by mcollina** [comment]
Fundamentally the license checker is wrong. We only care about the production dependencies, while it checks for everything.

https://www.npmjs.com/package/license-checker is a good module to do license checking and what we use in Fastify: https://github.com/fastify/fastify/blob/438369fe189c8ed33827251305bcaeacdcbe3ea7/.github/workflows/ci.yml#L98-L100 https://github.com/fastify/fastify/blob/438369fe189c8ed33827251305bcaeacdcbe3ea7/package.json#L14

**Pull request merged**
